### ISSUE TITLE
跑起来报错，建议加上依赖环境的版本

### ISSUE THREAD

**Issue by shikingram** [zoudingyi/fish-touching-bot#4]
```
╭─ ~/sourceCode/fish-touching-bot  on main !1 ··················································································································· ✔  at 11:19:21 ─╮
╰─ npm run dev                                                                                                                                                                   ─╯

> fish-touching-bot@1.0.0 dev
> nodemon --ext js,ts --exec "./node_modules/.bin/ts-node src/index.ts"

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,ts
[nodemon] starting `./node_modules/.bin/ts-node src/index.ts`
/Users/kingram/sourceCode/fish-touching-bot/node_modules/ts-node/src/index.ts:750
    return new TSError(diagnosticText, diagnosticCodes);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/utils/broadcast.ts:80:7 - error TS2367: This condition will always return 'false' since the types 'number' and 'string' have no overlap.

80   if (month === '12') {
         ~~~~~~~~~~~~~~

    at createTSError (/Users/kingram/sourceCode/fish-touching-bot/node_modules/ts-node/src/index.ts:750:12)
    at reportTSError (/Users/kingram/sourceCode/fish-touching-bot/node_modules/ts-node/src/index.ts:754:19)
    at getOutput (/Users/kingram/sourceCode/fish-touching-bot/node_modules/ts-node/src/index.ts:941:36)
    at Object.compile (/Users/kingram/sourceCode/fish-touching-bot/node_modules/ts-node/src/index.ts:1243:30)
    at Module.m._compile (/Users/kingram/sourceCode/fish-touching-bot/node_modules/ts-node/src/index.ts:1370:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/kingram/sourceCode/fish-touching-bot/node_modules/ts-node/src/index.ts:1374:12)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19) {
  diagnosticText: "\x1B[96msrc/utils/broadcast.ts\x1B[0m:\x1B[93m80\x1B[0m:\x1B[93m7\x1B[0m - \x1B[91merror\x1B[0m\x1B[90m TS2367: \x1B[0mThis condition will always return 'false' since the types 'number' and 'string' have no overlap.\n" +
    '\n' +
    "\x1B[7m80\x1B[0m   if (month === '12') {\n" +
    '\x1B[7m  \x1B[0m \x1B[91m      ~~~~~~~~~~~~~~\x1B[0m\n',
  diagnosticCodes: [ 2367 ]
}
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by zoudingyi** [comment]
wechaty-puppet-wechat 协议最近好像也不能用了。具体的情况请查看wechaty官方或者更换其他协议吧。

**Comment by zoudingyi** [comment]
因为微信官方更新，wechaty-puppet-wechat 无法使用。
